# IMPORTING ALL THE REQUIRED LBRARIES

In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# READING THE DATASET

In [104]:
df = pd.read_csv('Employee_attrition.csv')
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

# CHECKING THE SHAPE OF DATASET

In [105]:
df.shape

(1470, 35)

# CHECKING DATATYPES OF EACH COLUMN

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

# CONVERTING CATEGORICAL VALUES INTO NUMERICAL VALUES

In [107]:
#Attrition column
df['Attrition'] = df['Attrition'].replace({'Yes':1,'No':0})

#BusinessTravel column
df['BusinessTravel'] = df['BusinessTravel'].replace({'Travel_Rarely':0,'Travel_Frequently':1,'Non-Travel':2})

#Department column
df['Department'] = df['Department'].replace({'Sales':0,'Research & Development':1,'Human Resources':2})

#EducationField column
df['EducationField'] = df['EducationField'].replace({'Life Sciences':0,'Medical':1,'Marketing':2,'Technical Degree':3,
                                                     'Human Resources':4,'Other':5})

#GEnder column
df['Gender'] = df['Gender'].replace({'Female':1,'Male':0})

#JobRole column
df['JobRole'] = df['JobRole'].replace({'Sales Executive':0,'Research Scientist':1,'Laboratory Technician':2,'Manufacturing Director':3,
                                       'Healthcare Representative':4,'Manager':5,'Sales Representative':6,'Research Director':7,
                                       'Human Resources':8})

#Maritalstatus column
df['MaritalStatus'] = df['MaritalStatus'].replace({'Single':0,'Married':1,'Divorced':2})

#overtime column
df['OverTime'] = df['OverTime'].replace({'Yes':1,'No':0})

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   int64 
 2   BusinessTravel            1470 non-null   int64 
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   int64 
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   int64 
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   int64 
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [109]:
df = df.drop(['Over18'],axis=1)

# CHECKING CORRELATION BETWEEN DEPENDENT AND INDEPENDENT VARIABKES

In [110]:
for i in df.columns:
  print(i,'----------->',df['Attrition'].corr(df[i]))
  print('')

Age -----------> -0.15920500686577926

Attrition -----------> 1.0

BusinessTravel -----------> -7.377694602225551e-05

DailyRate -----------> -0.05665199186762916

Department -----------> -0.06399059633809008

DistanceFromHome -----------> 0.07792358295570351

Education -----------> -0.031372819640049295

EducationField -----------> 0.05156704570591742

EmployeeCount -----------> nan

EmployeeNumber -----------> -0.01057724275924313

EnvironmentSatisfaction -----------> -0.10336897833793617

Gender -----------> -0.029453253175141646

HourlyRate -----------> -0.006845549572139851

JobInvolvement -----------> -0.13001595678605318

JobLevel -----------> -0.16910475093102645

JobRole -----------> -0.027930476081942206

JobSatisfaction -----------> -0.10348112606902116

MaritalStatus -----------> -0.16207023465701428

MonthlyIncome -----------> -0.15983958238498835

MonthlyRate -----------> 0.015170212530471426

NumCompaniesWorked -----------> 0.043493739057813625

OverTime -----------> 0.2

# DROPING UNWANTED COLUMNS

In [111]:
df = df.drop(['Education','EducationField','EmployeeCount','DailyRate','HourlyRate','OverTime','StandardHours','TrainingTimesLastYear',
              'StockOptionLevel','BusinessTravel','JobLevel','MonthlyRate','NumCompaniesWorked'],axis=1)

In [112]:
len(df.columns)

21

In [113]:
df.columns

Index(['Age', 'Attrition', 'Department', 'DistanceFromHome', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'JobInvolvement', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'TotalWorkingYears', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

# DESCRIBTION OF EACH COLUMN

In [114]:
for col in df.columns:
  print(col)
  print("---------------------------------")
  print(df[col].describe())
  print()

Age
---------------------------------
count    1470.000000
mean       36.923810
std         9.135373
min        18.000000
25%        30.000000
50%        36.000000
75%        43.000000
max        60.000000
Name: Age, dtype: float64

Attrition
---------------------------------
count    1470.000000
mean        0.161224
std         0.367863
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: Attrition, dtype: float64

Department
---------------------------------
count    1470.000000
mean        0.739456
std         0.527792
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: Department, dtype: float64

DistanceFromHome
---------------------------------
count    1470.000000
mean        9.192517
std         8.106864
min         1.000000
25%         2.000000
50%         7.000000
75%        14.000000
max        29.000000
Name: DistanceFromHome, dtype: float64

EmployeeNumber
-

# CHECKING ALL THE UNIQUE VALUES IN EACH FEATURE

In [115]:
for i in df.columns:
  print(i)
  print("---------------------")
  print(df[i].unique())
  print("")

Age
---------------------
[41 49 37 33 27 32 59 30 38 36 35 29 31 34 28 22 53 24 21 42 44 46 39 43
 50 26 48 55 45 56 23 51 40 54 58 20 25 19 57 52 47 18 60]

Attrition
---------------------
[1 0]

Department
---------------------
[0 1 2]

DistanceFromHome
---------------------
[ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]

EmployeeNumber
---------------------
[   1    2    4 ... 2064 2065 2068]

EnvironmentSatisfaction
---------------------
[2 3 4 1]

Gender
---------------------
[1 0]

JobInvolvement
---------------------
[3 2 4 1]

JobRole
---------------------
[0 1 2 3 4 5 6 7 8]

JobSatisfaction
---------------------
[4 2 3 1]

MaritalStatus
---------------------
[0 1 2]

MonthlyIncome
---------------------
[5993 5130 2090 ... 9991 5390 4404]

PercentSalaryHike
---------------------
[11 23 15 12 13 20 22 21 17 14 16 18 19 24 25]

PerformanceRating
---------------------
[3 4]

RelationshipSatisfaction
---------------------
[1 4 2 3]

Tota

# DIVIDING DEPENDENT AND INDEPENDENT VARIABLES 

In [116]:
y = df['Attrition']
x = df.drop(['Attrition'],axis=1)

# IMPORTING ALL THE REQUIRED MODELS AND METRICS

In [117]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score,confusion_matrix

# SPLITTING THE DATASET INTO TRAINING AND TESTING

In [118]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# MAKING PIPELINE FOR EVERY MODEL

In [119]:
mdl_1 = make_pipeline(StandardScaler(), LogisticRegression()) 
mdl_2 = make_pipeline(StandardScaler(), DecisionTreeClassifier()) 
mdl_3 = make_pipeline(StandardScaler(), RandomForestClassifier())
mdl_4 = make_pipeline(StandardScaler(), KNeighborsClassifier())
mdl_5 = make_pipeline(StandardScaler(), SVC()) 
mdl_6 = make_pipeline(StandardScaler(), GaussianNB())

# FITTING AND PREDICTING THE MODEL

In [120]:
mdls = [mdl_1,mdl_2,mdl_3,mdl_4,mdl_5,mdl_6]

for i in mdls:
  print("")
  i.fit(x_train,y_train)
  y_pred = i.predict(x_test)
  print("   CONFUSION MATRIX ")
  print("  ",confusion_matrix(y_pred,y_test))
  print("")
  print("    ACCURACY SCORE ")
  print("  ",accuracy_score(y_pred,y_test))
  print("----------------------------------")
  print("")
  print("")
  print("")



   CONFUSION MATRIX 
   [[252  34]
 [  3   5]]

    ACCURACY SCORE 
   0.8741496598639455
----------------------------------




   CONFUSION MATRIX 
   [[214  31]
 [ 41   8]]

    ACCURACY SCORE 
   0.7551020408163265
----------------------------------




   CONFUSION MATRIX 
   [[251  35]
 [  4   4]]

    ACCURACY SCORE 
   0.8673469387755102
----------------------------------




   CONFUSION MATRIX 
   [[249  35]
 [  6   4]]

    ACCURACY SCORE 
   0.8605442176870748
----------------------------------




   CONFUSION MATRIX 
   [[255  37]
 [  0   2]]

    ACCURACY SCORE 
   0.8741496598639455
----------------------------------




   CONFUSION MATRIX 
   [[226  18]
 [ 29  21]]

    ACCURACY SCORE 
   0.8401360544217688
----------------------------------





# HIGH ACCURACY SCORE MODELS

### Model-1
### -----------------------------------------
### LogisticRegression
### Accuracy_Score ------> 87.41


### Model-2
### -----------------------------------------

### RandomForest Classifier
### Accuracy_Score ------> 87.41


### Model-3
### -----------------------------------------

### DecisionTree Classifier
### Accuracy_Score -----> 87.07
### -----------------------------------------

# SAVING THE MODEL IN PICKLE FILE

In [121]:
import pickle

In [122]:
filename = 'employee_attrition.pkl'
pickle.dump(mdl_5, open(filename, 'wb'))